# Generated by Django 3.1.4 on 2020-12-28 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='relator',
            new_name='realtor',
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
