# Generated by Django 3.1.4 on 2020-12-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20201228_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtor',
            new_name='realtor_id',
        ),
    ]
