# Generated by Django 3.1.4 on 2020-12-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20201224_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
